#!/usr/bin/env bash
set -Eeuo pipefail

# ==== Dependency checks ====
need() { command -v "$1" >/dev/null 2>&1 || { echo "[ERR] Missing dependency: $1" >&2; exit 1; }; }
need kubectl
need yq
need envsubst

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ==== Load environment variables from custom-values.yaml ====
# shellcheck disable=SC1091
source ./load-env.sh

# ==== Helper functions ====

# envsubst with a whitelist of variables to prevent accidental substitution of $1/$2 inside prometheus.yml
render_apply_vars() {
  local vars="$1"; shift
  local file="$1"
  envsubst "$vars" < "$file" | kubectl apply -f -
}

# Apply PVC; remove storageClassName if STORAGE_CLASS is empty (use cluster default)
render_apply_pvc() {
  local file="$1"
  local rendered
  rendered=$(envsubst '${NAMESPACE}${STORAGE_CLASS}${PROMETHEUS_SIZE}${GRAFANA_SIZE}' < "$file")
  if [[ -z "${STORAGE_CLASS:-}" || "${STORAGE_CLASS}" == '""' ]]; then
    echo "$rendered" | yq 'del(.spec.storageClassName)' | kubectl apply -f -
  else
    echo "$rendered" | kubectl apply -f -
  fi
}

# ==== Namespace & RBAC ====
render_apply_vars '${NAMESPACE}' manifests/namespace/namespace.yaml
render_apply_vars '${NAMESPACE}' manifests/rbac/prometheus-rbac.yaml

# ==== Persistent Volume Claims ====
render_apply_pvc manifests/pvc/prometheus-pvc.yaml
render_apply_pvc manifests/pvc/grafana-pvc.yaml

# ==== Grafana admin credentials ====
kubectl -n "$NAMESPACE" delete secret grafana-admin-credentials --ignore-not-found
kubectl -n "$NAMESPACE" create secret generic grafana-admin-credentials \
  --from-literal=admin-user="$GRAFANA_USER" \
  --from-literal=admin-password="$GRAFANA_PASS"

# ==== Prometheus ====
# ConfigMap only needs NAMESPACE substitution; keep $1/$2 in relabel_configs intact
render_apply_vars '${NAMESPACE}' manifests/prometheus/configmap.yaml
render_apply_vars '${NAMESPACE}' manifests/prometheus/deployment.yaml
render_apply_vars '${NAMESPACE}' manifests/prometheus/service.yaml

# ==== Grafana ====
render_apply_vars '${NAMESPACE}' manifests/grafana/deployment.yaml
render_apply_vars '${NAMESPACE}' manifests/grafana/service.yaml

# ==== Cert-manager ClusterIssuer (staging/prod) ====
case "$CLUSTER_ISSUER" in
  letsencrypt-staging) render_apply_vars '${CERTMANAGER_EMAIL}${INGRESS_CLASS}' manifests/tls/tls-staging.yaml ;;
  letsencrypt-prod)    render_apply_vars '${CERTMANAGER_EMAIL}${INGRESS_CLASS}' manifests/tls/tls-prod.yaml ;;
  *) echo "[WARN] Unknown CLUSTER_ISSUER=$CLUSTER_ISSUER. Falling back to tls-prod.yaml." >&2
     render_apply_vars '${CERTMANAGER_EMAIL}${INGRESS_CLASS}' manifests/tls/tls-prod.yaml ;;
esac

# ==== Certificate (explicit creation to ensure grafana-tls Secret is generated by cert-manager) ====
render_apply_vars '${NAMESPACE}${DOMAIN}${CLUSTER_ISSUER}' manifests/tls/certificate.yaml

# ==== Ingress (root domain -> Grafana, includes cluster-issuer annotation) ====
render_apply_vars '${NAMESPACE}${DOMAIN}${INGRESS_CLASS}${CLUSTER_ISSUER}' manifests/ingress/ingress.yaml

# ==== Rollout status ====
kubectl -n "$NAMESPACE" rollout status deploy/prometheus --timeout=180s || true
kubectl -n "$NAMESPACE" rollout status deploy/grafana --timeout=180s || true

# ==== TLS status summary ====
echo
kubectl -n "$NAMESPACE" get certificate,gateway,httproute 2>/dev/null || true
kubectl -n "$NAMESPACE" get secret grafana-tls 2>/dev/null || true
kubectl -n "$NAMESPACE" get ingress grafana-ingress -o wide 2>/dev/null || true

echo
echo "[DONE] Deployment completed successfully for namespace: $NAMESPACE"
echo "Grafana is available at: https://$DOMAIN/"
